## 第8题，写出执行结果，并解释原因

```js
let x, y;
try {
  throw new Error();
} catch (x) {
  x =1;
  y=2;
  console.log(x);
}
console.log(x);
console.log(y);
```

[答案](https://github.com/lgwebdream/FE-Interview/issues/71)